version: "3.9"
services:
    app:
        build:
            context: .
            target: app-server
        ports:
        - "5000:5000"
    ldap_server:
        build:
            context: .
            target: ldap-server
            # login DN: cn=admin,dc=techinterview,dc=com
        ports:
            - 389:389
        volumes:
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d
    ldap_server_admin:
        image: osixia/phpldapadmin:0.7.2
        ports:
            - 8090:80
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap_server
            PHPLDAPADMIN_HTTPS: 'false'
        depends_on:
            - ldap_server

volumes:
    ldap_data:
    ldap_config: